---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /q/metrics
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/scrape: "true"
  labels:
    {{- include "customer.labels" . | nindent 4 }}
  name: {{ include "customer.fullname" . }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "customer.selectorLabels" . | nindent 4 }}
