---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  # annotations:
  #   jkube.eclipse.org/git-commit: bb01eb50a167fb544483004b02c52a633c394021
  #   app.openshift.io/vcs-ref: helm-deployment
  #   jkube.eclipse.org/git-branch: helm-deployment
  labels:
    {{- include "customer.labels" . | nindent 4 }}
  name: {{ include "customer.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    {{- include "customer.selectorLabels" . | nindent 4 }}
  strategy:
    {{- toYaml .Values.podStrategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "customer.selectorLabels" . | nindent 8 }}
      name: {{ include "customer.fullname" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "customer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: quarkus
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.liveness | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readiness | nindent 10 }}
        startupProbe:
          {{- toYaml .Values.startup | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  triggers:
  - type: ConfigChange
