apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: EP288_TASK88_APPLICATION
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-repo-name
    value: $(body.repository.name)
  - name: git-revision
    value: $(body.after)